# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c374789866e98428b21bf5e061464b1e30807dd07dc6538a1e9e9659f24cba6edbde4795c267b5415e509de89c041a23364f32cda437f3f8d61547d1cc9a89b

test:
  secret_key_base: 45d0310910fdce086505708bc94251c89098f0134a4603cd38ec6be1df3dd2d0eee67fa2efa642db7d74051527f345b9bd9c139da16a619101dae0e353929634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
